openapi: 3.0.1
info:
  title: PAN -Protean
  description: ''
  version: 1.0.0
tags: []
paths:
  /qa/panverification/1.3/en:
    post:
      summary: PAN Verification
      deprecated: false
      description: 
      tags: []
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          example: application/json
          schema:
            type: string
        - name: client-id
          in: header
          description: ''
          required: true
          example: UlNoNEFaSXFuSTNKQ09oMEthTFhWVWQyek9vYQ==
          schema:
            type: string
        - name: provider
          in: header
          description: ''
          required: true
          example: '106'
          schema:
            type: string
        - name: api-key
          in: header
          description: ''
          required: true
          example: 434950ee34353tty33463399
          schema:
            type: string
        - name: x-sp-userid
          in: header
          description: ''
          required: true
          example: V0024301
          schema:
            type: string
        - name: x-sp-record-count
          in: header
          description: ''
          required: true
          example: '1'
          schema:
            type: string
        - name: x-sp-version
          in: header
          description: ''
          required: true
          example: '4'
          schema:
            type: string
        - name: TETETETE
          in: header
          description: ''
          required: true
          example: AGSFAGF
          schema:
            type: string
        - name: Content-Type
          in: header
          description: ''
          required: true
          example: application/json
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: true
          example: >-
            Bearer
            eyJ4NXQiOiJNR1JqTWpSaVlqVTBNVEpqWVRsaU1tSmpNMlUxT0RWbU56UmxOamN4WkRZeFptWXlNRFUwWWciLCJraWQiOiJOVFJoT0RkallqazNNR1UzTldGaU9EYzBaREppTmpsbE9URmtPVGt6TkRBME1tSXpNV1l4TkdNd05qazFaak5pTWpsaU4yTTFOMlpoTnpOalkyTTJPQV9SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJyYmloaW50YWRtaW4iLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6IlJTaDRBWklxbkkzSkNPaDBLYUxYVlVkMnpPb2EiLCJuYmYiOjE3NTMyNjMyOTEsImF6cCI6IlJTaDRBWklxbkkzSkNPaDBLYUxYVlVkMnpPb2EiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvaWRlbnRpdHkubm9ucHJvZC5yYmlodWIuaW9cL29hdXRoMlwvdG9rZW4iLCJleHAiOjE3NTMzMDY0OTEsImlhdCI6MTc1MzI2MzI5MSwianRpIjoiNmZkMTk3ZmEtMjI4OC00NDcyLWJmMDctMjY2ZmJiOTRlOTY2In0.Seo_3cZcTCJEZxjHttUrYzmyghlLqs3WQjJaa8rys9N8gS-s9rrFzdUv0UeiJwMF1yck6cFxMWJOi7Z5ijZauTygRy_o2Iovlp7DauonaJki5BI8toBmFkz4TPtSqqkDrgYUAGnHp5twJfPcV5F8hw90Exmq2lI8Lz9MubZNJEZN9wAjUI59xHsPtRwLxfSvBHLVCBIT5qTUdloFNGSEqrBoe9PQVkDfVSMUxGQv19v6R8KDmueyqfmA1-cA_LU1p-6YdJAbEBQxAJ2lt9S65ApJOXPZt69E4edZOYqOZ7Z3402RgQsH62cTP9BwDe4yfLGPJ5haZn-AZNdVcrgaJQ
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                meta:
                  type: object
                  properties:
                    ver:
                      type: string
                    ts:
                      type: string
                    txncode:
                      type: string
                  required:
                    - ver
                    - ts
                    - txncode
                data:
                  type: object
                  properties:
                    payload:
                      type: string
                    sessionId:
                      type: string
                    sessionKey:
                      type: string
                  required:
                    - payload
                    - sessionId
                    - sessionKey
                hmac:
                  type: string
              required:
                - meta
                - data
                - hmac
            example:
              meta:
                ver: '1.3'
                ts: 2025-08-05T11:43:22+0530
                txncode: Rameshwar0006
              data:
                payload: >-
                  WDoUcYEappsAbqd2pThW27ht8KDKmG2oi0dygVRpY74IuK+97MNnxRtmO/ayUsI6MeE702gkcf0LKjRCfXOVIiibuR1JRRRIhUIIgf1XDhNSa3ENknRmB25rKX6ayHj5ypMg4NDRgrWC
                sessionId: >-
                  ln+OCfvHxWMRZzBxncegakb9jMjd/Iuufipoz8kk45kAHFnSDkUVkxqYcezJmv54h+Bq5DvvYIpNVuTX6mkRx69z4zEdsPvcrL2DJ+OTcKA8yh0u8VvfPS2UoTst2KaIA2e/BiJMG0GFc0+cDJXxToowmIQbhTKqmmqUvraUmVZOR80fdzsCzMeqPRlZHEU4MgdRwwVujlpfPfIe8jix5xWbyzzitqehD8cAF5f7dXhbIWwtGvhTNQQWxk4F5awZq0BQ2cbNiTPbE3XRATBygbzKZweERqKgsEkwsPvCgvv/h/kbAUeFP+MhCbJjbIVRpDhc/z2f10y+x+Gn3niTgg==
                sessionKey: >-
                  0s0edeE2U5eSmOvgD+gjqs5b/fzMy80FMCLVRsSap0YN1vK7fmxdXQcPxpQLEButtXbrCTKdRmpsjTbc1B+ur2klEOnk07VvHzb87Fu+3anoP1XClESfspLGKGuSBm/uHiC5oMQOnRu/kxINtD/SOIj8OObsfmeVR98197AEpKVTI+gE0Y4r0oAEULAC5K4luA00YeRtjb8anPhrhZtU8sUH02KegtVQEkHFoFF7lrL5VwmheibLGJv9R2QhOTv4/JTB9XFfSmcYVRFIOoGrLh/XfHt6AWO0JyqUWqvfj6rCUCBdADZLmPErD20WwzIer3wxx9/qn6i8U0liTM7t6g==
              hmac: WKljGvYklRgU3reW7KNmUGa2W55zRF/8b/bnw/JWYo4=
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      errcode:
                        type: string
                      status:
                        type: string
                      info:
                        type: string
                    required:
                      - errcode
                      - status
                      - info
                  data:
                    type: object
                    properties:
                      response_Code:
                        type: string
                      outputData:
                        type: array
                        items:
                          type: object
                          properties:
                            fathername:
                              type: string
                            dob:
                              type: string
                            name:
                              type: string
                            pan_status:
                              type: string
                            pan:
                              type: string
                            seeding_status:
                              type: string
                    required:
                      - response_Code
                      - outputData
                  signature:
                    type: string
                  meta:
                    type: object
                    properties:
                      txncode:
                        type: string
                      ver:
                        type: string
                      ts:
                        type: string
                    required:
                      - txncode
                      - ver
                      - ts
                  hmac:
                    type: string
                  publickey:
                    type: string
                  sig-algo:
                    type: string
                required:
                  - result
                  - data
                  - signature
                  - meta
                  - hmac
                  - publickey
                  - sig-algo
              example:
                result:
                  errcode: E000
                  status: success
                  info: ''
                data:
                  response_Code: '1'
                  outputData:
                    - fathername: ''
                      dob: 'Y'
                      name: 'Y'
                      pan_status: E
                      pan: AAAPB2117A
                      seeding_status: R
                signature: >-
                  MGYCMQCViV1xuDt8mbksn+bJFLVJ4WT40NxAwr/NcBFIBzeYZk6ZZsgYiYmHPHn0JYTbWaQCMQCQLdcg/Fk1Prw7PxrPNYjIO5lZERTzYQ62gGJnnoHunZFBT+MBv+6eClo+4luWXx4=
                meta:
                  txncode: Rameshwar0006
                  ver: '1.3'
                  ts: 2025-08-05T11:43:39+0530
                hmac: FSaGxhxwgYKIJ4aU0dnnMvI1M9QKO1h/Au01X+cijI8=
                publickey: >-
                  MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEKulxpinET1WoqVhiCpEQCNQQBtMRgVvjnvxfTINwr1ST7s+KoJuEp/ciPAnYZHZ5soGMZtLBZRRhEJnvvhlXClUiojiwLnpE0jxBhrLO+5wwUTRLFHLpsoA45/p5B0Hz
                sig-algo: SHA256withECDSA
          headers: {}
        x-200:Failure:
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      errcode:
                        type: string
                      status:
                        type: string
                      info:
                        type: string
                    required:
                      - errcode
                      - status
                      - info
                  data:
                    type: object
                    properties: {}
                  signature:
                    type: string
                  meta:
                    type: object
                    properties:
                      txncode:
                        type: string
                      ver:
                        type: string
                      ts:
                        type: string
                    required:
                      - txncode
                      - ver
                      - ts
                  hmac:
                    type: string
                  publickey:
                    type: string
                  sig-algo:
                    type: string
                required:
                  - result
                  - data
                  - signature
                  - meta
                  - hmac
                  - publickey
                  - sig-algo
              example:
                result:
                  errcode: E045
                  status: failed
                  info: Missing mandatory header parameter
                data: {}
                signature: >-
                  MGQCMDZhtM25O1bIxVjWNwOsMR+3C4nvDsWeSc6K+xsJIyv1tcUgStK7931y/In5aFimlgIwU1OWXmpTwjiy5DaW5VRNj8VHKcYKWbazdPLFI5YhirHnJEuXPhOYM0RG0vF47Jct
                meta:
                  txncode: Rameshwar0006
                  ver: '1.3'
                  ts: 2025-08-05T11:44:32+0530
                hmac: WKljGvYklRgU3reW7KNmUGa2W55zRF/8b/bnw/JWYo4=
                publickey: >-
                  MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEKulxpinET1WoqVhiCpEQCNQQBtMRgVvjnvxfTINwr1ST7s+KoJuEp/ciPAnYZHZ5soGMZtLBZRRhEJnvvhlXClUiojiwLnpE0jxBhrLO+5wwUTRLFHLpsoA45/p5B0Hz
                sig-algo: SHA256withECDSA
          headers: {}
      security:
        - bearer: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers: []
security: []
