name: Deploy to Azure Web App

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/deploy.yml'
      - 'docs/**'
      - 'src/**'
      - 'static/**'
      - 'docusaurus.config.ts'
      - 'package.json'
      - 'sidebars.ts'
      - 'specs/**'

env:
   AZURE_WEBAPP_NAME: uliapidocs 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docusaurus site
        run: yarn build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./build
